### ISSUE TITLE
Show slot id after initialization

### ISSUE THREAD

**Issue by beatriztavares** [opendnssec/SoftHSMv2#334] opened 2017-07-21 14:23 UTC
Issue on https://github.com/opendnssec/SoftHSMv2/issues/225 still happening on Ubuntu.

1 - I clone of this repo and I run through the install instructions. 
2 - run **softhsm2-util --show-slots** to see the available slots. Slot 0 will present as empty, as expected.
3 - run **softhsm2-util --init-token --slot 0 --label "test" --pin 123456 --so-pin 123456**.
4 - Run **softhsm2-util --show-slots** again and the token I just created is under Slot **812164394**.

**Comment by bellgrim** [comment] 2017-07-22 20:49
Yes, and it still is expected behavior. 

Did you not get a new slot ID from the output in step 3?

**Comment by beatriztavares** [comment] 2017-07-24 14:19
After step 3 I have 2 slots: Slot **812164394** (where token is located) and Slot **1**

**Comment by bellgrim** [comment] 2017-07-24 18:08
Yes, this is not an issue. It is expected behavior. I see that the documentation needs to be more clear on this.

**Comment by jelu** [comment] 2017-08-01 11:48
Would have preferred a major version bump for this breaking change and/or a command line option (`--reassign-slot`) so things (like Perl module tests `Crypt::PKCS11`) don't just break all of the sudden.

**Comment by bellgrim** [comment] 2017-08-22 06:22
The token is not reassigned to a new slot right after initialization, this will only happen once the application reinitialize the library. It will have same slot number as long as you interact with the token in the same context. However, if you are running consecutive command using separate processes (e.g. initializing token and then listing the slots), then you will have the token in a different slot.

This behavior is in accordance with the specification. The calling application should not rely on a slot number, since this may change over time. It should use the token label (or serial if you have multiple tokens with the same label) to find to correct token.

**Comment by bellgrim** [comment] 2017-08-22 06:23
Sorry, will reopen this issue since we need to update the documentation to make this more clear.

**Comment by jelu** [comment] 2017-08-22 06:54
Thanks @bellgrim, is this SoftHSM specification or PKCS#11 v2.4+?

**Comment by bellgrim** [comment] 2017-08-22 14:08
@jelu PKCS#11

**Comment by bellgrim** [comment] 2017-09-28 07:32
Documentation has now been updated

**Closed by bellgrim** 2017-09-28 07:32 UTC
Labels: enhancement
