### ISSUE TITLE
BUG: Definition of CK_GCM_PARAMS is NOT correct

### ISSUE THREAD

**Issue by xipki** [opendnssec/SoftHSMv2#488] opened 2019-06-24 21:45 UTC
The definition of ck_gcm_params in `pkcs11.h` is NOT correct.

```
struct ck_gcm_params {
  unsigned char *iv_ptr;
  unsigned long iv_len;
  unsigned long iv_bits;
  unsigned char *aad_ptr;
  unsigned long aad_len;
  unsigned long tag_bits;
};
```
should be changed to

```
struct ck_gcm_params {
  unsigned char *iv_ptr;
  unsigned long iv_len;
  unsigned char *aad_ptr;
  unsigned long aad_len;
  unsigned long tag_bits;
};
```

The line  `unsigned long iv_bits;` should be removed.

The official Definition can be found in Section 2.12.3 of http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/os/pkcs11-curr-v2.40-os.html.

Note that the definition with iv_bits comes from the http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/pkcs11t.h. This, however, conflicts the spec.

**Comment by jariq** [comment] 2019-06-25 04:31
Duplicate of https://github.com/opendnssec/SoftHSMv2/pull/481.

**Comment by rijswijk** [comment] 2019-06-25 05:33
Closing, duplicate of #481 (thanks @jariq)

**Closed by rijswijk** 2019-06-25 05:33 UTC
