### ISSUE TITLE
Show slot id after initialization

### ISSUE THREAD

**Issue by anitgandhi** [opendnssec/SoftHSMv2#225] opened 2016-08-16 16:07 UTC
Whenever I run `softhsm2-util --init-token` on a given free slot, it changes the slot id to something very large. See screenshot for example. 

Steps taken:
1. Fresh clone of this repo and I run through the install instructions - no problems here
2. Run `softhsm2-util --show-slots` to see the available slots. Slot 0 will present as empty, as expected. 
3. Run `softhsm2-util --init-token --slot 0 --label "test" --pin 1234 --so-pin 1234`. 
4. Run `softhsm2-util --show-slots` again and the token I just created is under Slot 1004965189 (for example, could be any large number usually). 

This happens on Mac and Ubuntu from my testing. 

I'm not sure if this is by design or if I'm missing something.

**Comment by anitgandhi** [comment] 2016-08-16 17:01
Interestingly this doesn't happen on the `master` branch...

**Comment by bellgrim** [comment] 2016-08-16 18:35
This is by design. See #199.

From the NEWS file:

> Issue #199: The token serial number will be used when setting the slot number. The serial number is set after the token has been initialized. (Patch from Lars Silvan)

**Comment by matthauck** [comment] 2016-08-16 20:23
Would it be possible for softhsm2-util to display the new slot ID in the output? It would be nice to be able to know the new ID immediately at initialization time.

**Comment by bellgrim** [comment] 2016-08-17 17:15
The slot ID is only updated after the library is reinitialized.

softhsm2-util could show the new slot ID if it reinitialize the library and search for a token matching the given label.

**Comment by bellgrim** [comment] 2017-03-31 18:16
Fixed in #296

**Closed by bellgrim** 2017-03-31 18:16 UTC
Labels: enhancement

**Comment by beatriztavares** [comment] 2017-07-21 14:15
Still happening on Ubuntu
