### ISSUE TITLE
Structure packing alignment

### ISSUE THREAD

**Issue by jumpifnotzero** [opendnssec/SoftHSMv2#471] opened 2019-04-17 22:13 UTC
Hi,

SoftHSM does not pack structures with 1-byte alignment, breaking ABI compatibility with other PKCS#11 code (see http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/pkcs11-base-v2.40-errata01-os-complete.html#_Toc441755746).

This is easily evident with the CK_TOKEN struct. The flags/libraryDescription are aligned to compiler-specific boundaries, causing a valid client to read "junk" padding bytes into the libraryDescription, which can be invalid UTF-8. I have not checked alignment of other structs.

The previous version of the pkcs11 headers (pre p11-kit) made reference to the requirement to set packing alignment (line 27 of https://github.com/opendnssec/SoftHSMv2/blob/ab7256453a4be6f34fa603459b24f0d39569a7b1/src/lib/pkcs11/pkcs11.h). This note appears to have been lost in the change to the p11-kit headers.

I'm running SoftHSM 2.5 on 64-bit Ubuntu-18.04. Below is a memory dump of the CK_TOKEN struct; padding bytes are 0x22-0x2A.
```
00000000: 0228 536f 6674 4853 4d20 2020 2020 2020  .(SoftHSM       
00000010: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000020: 2020 10ff ffff a813 7f00 0000 0000 0000    ..............
00000030: 0000 0049 6d70 6c65 6d65 6e74 6174 696f  ...Implementatio
00000040: 6e20 6f66 2050 4b43 5331 3120 2020 2020  n of PKCS11     
00000050: 2020 2002 05
```

**Comment by jumpifnotzero** [comment] 2019-04-17 23:21
Wrapping the `struct ck_info` with a `#pragma` directive gives the expected layout.
```c
#pragma pack(push, 1)
struct ck_info
{
  struct ck_version cryptoki_version;
  unsigned char manufacturer_id[32];
  ck_flags_t flags;
  unsigned char library_description[32];
  struct ck_version library_version;
};
#pragma pack(pop)
```
This is a platform-specific and targeted example to illustrate expected behaviour (https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Structure-Layout-Pragmas.html#Structure-Layout-Pragmas). Unfortunately I do not know how to set alignment in a cross-platform manner for your supported architectures.

The resulting memory dump:
```
00000000: 0228 536f 6674 4853 4d20 2020 2020 2020  .(SoftHSM       
00000010: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000020: 2020 0000 0000 0000 0000 496d 706c 656d    ........Implem
00000030: 656e 7461 7469 6f6e 206f 6620 504b 4353  entation of PKCS
00000040: 3131 2020 2020 2020 2020 0205
```

[The Lost Art of Structure Packing # Overriding alignment rules](http://www.catb.org/esr/structure-packing/#_overriding_alignment_rules) seems informative.

**Comment by rijswijk** [comment] 2019-04-18 05:33
Do you know if the latest ```p11-kit``` headers perform this packing correctly? It seems to me this is something that must be solved in the PKCS #11 header files rather than in the SoftHSM codebase.

**Comment by rijswijk** [comment] 2019-04-18 05:34
Never mind, I read the blob you referenced. We will look in to this.

**Comment by rijswijk** [comment] 2019-04-18 05:55
So, I had a look at the headers; it seems that the ```p11-kit``` header files do modify structure packing, but only for the Win32 build. This pragma setting is changed in ```cryptoki.h```, which is the _only_ header file that applications that use PKCS #11 should be including. I also looked at older versions of the PKCS #11 headers ([which can very helpfully be found here](https://github.com/Pkcs11Interop/PKCS11-SPECS)), and the behaviour is the same in those as well, only for Win32 is the pragma set. Given that this has been the case for years, it seems inevitable that all non-Win32 builds don't adhere to what the hints in ```pkcs11.h``` say, because software that builds based on the spec-supplied header files (as they should) will never set this pragma because ```cryptoki.h``` doesn't do it. 

SoftHSM has also always used the spec-supplied headers and only switched to ```p11-kit``` headers due to IPR concerns. If this had been a problem, I would have expected the many application developers that use SoftHSM to complain, so it seems that changing this pragma is perhaps unwise, because that *will* break things.

Which leads me to the question: how exactly are you using SoftHSM? Is it through an application? (if so, can you provide a link), or is it your own code? If it is your own code, do you include ```cryptoki.h``` or ```pkcs11.h```?

**Comment by jariq** [comment] 2019-04-18 07:27
I can confirm that 1-byte alignment is in practice used only on Windows platform. See chapter *"Zeros and ones in the API-s"* in [Pkcs11Interop library architecture](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/4.1.1/doc/ARCHITECTURE.md#zeros-and-ones-in-the-api-s) for more details.

**Comment by rijswijk** [comment] 2019-04-18 07:31
Thanks for the confirmation @jariq 

@jumpifnotzero it would help to know with which software you see this problem, because perhaps the developers should be notified to fix the assumption that this alignment is used on all platforms.

**Comment by jumpifnotzero** [comment] 2019-04-18 15:59
I was developing a script using python-pkcs11 against softhsm, however things failed when I transferred that script to my AEP Keyper Plus. The AEP-supplied PKCS11 library does pack with 1-byte alignment in their linux-based libraries (at least the version I am using), which triggered UTF-8 decode failures in the python library.

So it appears the reference implementation, leaving alignment up to the implementation for UNIX-based systems, was unfortunately treated as complete, and thus we've now got a lot of software that has diverged from the spec (SoftHSM, OpenDNSSEC, python-pkcs11, p11-kit...).

Note that the PKCS11 2.40 spec states:
> Cryptoki structures are packed to occupy as little space as is possible.  Cryptoki structures SHALL be packed with 1-byte alignment.

So the technical committee dropped the waffle about alignment on various systems in favour of a hard requirement on implementations (SHALL is interpreted as described in RFC2119, i.e. SHALL == MUST). Are either of you involved in the PKCS11 3.0 draft, and willing to try and loosen that requirement to better reflect practice? Or how about a "PKCS11 flag day", where fix packing alignment across the board ;)

**Comment by rijswijk** [comment] 2019-04-18 17:25
Honestly, I'm not brave enough to get into the PKCS #11 standardisation tussle ;-). I have worked with libraries from various HSM manufacturers on Linux systems (notably nCipher/Thales, Safenet Luna and Utimaco HSM), and all of these use the platform packing pragmas so work out of the box with the header files from ```p11-kit```. I would guess that AEP is the "odd one out" in the bunch.

Doing a flag day for this sounds good on paper, but the sheer number of PKCS #11 implementations out there make that a practical impossibility in my book. Add to that that unlike for DNS, the majority of PKCS #11 implementations are closed source :-/. 

While you could argue that the implementations have diverged from the spec at least in spirit, it seems to be such common practice that I personally wouldn't be in favour of trying to change this. What does @jariq think?

**Comment by jumpifnotzero** [comment] 2019-04-18 20:11
The aim of changing the specification is to reduce the likelihood of interoperability issues from vendors that like to prioritize compliance (say, over market forces). I'm now looking to get a library from AEP that uses platform-specific alignment. You can consider this closed from my point of view.

**Comment by dengert** [comment] 2019-04-19 11:36
[PKCS #11 Cryptographic Token Interface Base Specification Version 2.40 Plus Errata 01](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/pkcs11-base-v2.40.doc) (Authoritative)

Refers to: [pkcs11.h](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/pkcs11.h) where it talks about Windows  alignment then in line 59-60 says:  
```
* In a UNIX environment, you're on your own for this.  You might
* not need to do (or be able to do!) anything.
```

**Comment by rijswijk** [comment] 2019-04-19 11:53
@jumpifnotzero would it make sense to add a compile-time option to SoftHSM to build with 1-byte structure packing? It would be a low prio change, but if you believe it would be useful to have we can add it to the backlog.

**Comment by dcleland** [comment] 2019-04-23 10:36
@dengert - The section you refer to in pkcs11.h is saying it is up to you to work out how to get 1-byte alignment on Unix systems, if it is even possible. It is possible on Intel (x86 and x86_64) but not on Sparc64, in my experience.

Full disclosure, I work on the Ultra Electronics Keyper Plus PKCS#11 library.

**Comment by jariq** [comment] 2019-04-23 11:13
> What does @jariq think?

We can argue over the wording of PKCS#11 specification all we want, it won't change the fact that none of the PKCS#11 enabled apps I've ever worked with on Linux (including Firefox and Thunderbird) was using 1-byte alignment. Therefore as far as SoftHSM is concerned I see no reason to change anything.

**Comment by rijswijk** [comment] 2019-04-23 11:24
> > What does @jariq think?
> 
> We can argue over the wording of PKCS#11 specification all we want, it won't change the fact that none of the PKCS#11 enabled apps I've ever worked with on Linux (including Firefox and Thunderbird) was using 1-byte alignment. Therefore as far as SoftHSM is concerned I see no reason to change anything.

Seconded, I'm closing this for now, if people are really interested in a SoftHSM build with 1-byte structure packing I would ask them to open a new issue with a feature request.

**Closed by rijswijk** 2019-04-23 11:24 UTC

**Comment by dengert** [comment] 2019-04-24 13:16
@dcleland The comments in pkcs11.h imply to me, that on some platforms, it is not possible to live up to the  1-byte alignment requirement in the main document. And it would be best to use the complier/OS defaults on alignment. This is what most PKCS11 programs do. 

Since you work on the Ultra Electronics Keyper Plus PKCS#11 library, maybe they have a way to make your libraries conform to the defacto pkcs11 standards on linux systems. You could provide two versions.  For which systems do you provide libraries? Do you pass PKCS11 structures to the AEP Keyper Plus? Do you provide the pkcs11.h?

I agree with @jumpifnotzero on " the technical committee dropped the waffle" and they should address it in header files with licences that can be used. It is a shame that there are so many versions of pkcs11.h out the field.

**Comment by dcleland** [comment] 2019-04-24 13:45
@dengert - As I said the only platform we cannot support 1-byte packing on is Sparc64.

We have been complying with the actual standard of 1 byte packing, on 32-bit and 64-bit Linux platforms, since 2001 so I don't think we will be changing our library and breaking our existing customers code.

We ship a pkcs11.h which sets 1-byte packing on all platforms, except Sparc64.

**Comment by dengert** [comment] 2019-04-24 14:56
@dcleland  Can you ship 2 versions: A 1-byte packing version and a compiler based aligned version? 
The rest of the PKCS11 unix world uses the compiler aligned rules.  

Sounds like just a recompile of the package with out the packing directive. 

Since you have been shipping since 2001, have you received any requests for compiler aligned libraries?

Going back to PKCS\#11 V2.11r1  2001 (V2.0.1 1997 has similar wording)  : "8.1	Structure packing 
"Cryptoki structures are packed to occupy as little space as is possible.  In particular, on the Win32 and Win16 platforms, Cryptoki structures should be packed with 1-byte alignment.  In a UNIX environment, it may or may not be necessary (or even possible) to alter the byte-alignment of structures."

Then in "8.3.3	Generic UNIX" there is no reference to doing any packing, leaving it up to the compiler. 

So what did you do in your 2001 releases for Unix? 

When did you start enforcing the 1-byte alignment on Unix? 

I would venture to say that most if not all of [List_of_applications_using_PKCS_11](https://en.wikipedia.org/wiki/List_of_applications_using_PKCS_11) do not enforce 1-byte alignment in Unix. 

Shipping 2 versions of your library would give you both a backward compatible version for your current customers and allow your libraries to work with the other packages and utilities such as p11-kit, pkcs11-tool, and p11tool.

**Comment by dcleland** [comment] 2019-04-24 15:47
@dengert - It is never just a re-compile, we would have to do a QA cycle on the platforms affected.

In the last 10 years there has never been a request for compiler aligned libraries. I know at least 7 of the apps in the list are used regularly with our product, so either they are using it on Windows, or they have compiled them on Linux using headers with correct alignment.

2001 was when Linux support was added to our product. Before that, and after, 1-byte alignment was used on ALL platforms except sparc64.

**Comment by dengert** [comment] 2019-04-24 19:52
@dcleland Do you mean the source for these libraries is available to (at least) your customers? 

If so, recompiling  "them on Linux using headers with correct alignment" could be the solution to the original issue. 

@jumpifnotzero  can you recompile them?

**Comment by rijswijk** [comment] 2019-04-24 19:55
While I think the discussion is useful, it is not really about SoftHSM any more, may I ask you to continue the discussion elsewhere?
