### ISSUE TITLE
CKA_ALWAYS_AUTHENTICATE not implemented

### ISSUE THREAD

**Issue by mouse07410** [opendnssec/SoftHSMv2#200] opened 2016-03-13 08:50 UTC
PIV standard (NIST 800-73) says that SIGN key (9C) should have the attribute "PIN Always" set. I.e., every operation on this private key should be immediately preceded by PIN authentication.

I'd like to see this behavior supported. 

Thanks!

**Comment by bellgrim** [comment] 2016-03-13 20:40
This is a duplicate of #141

**Closed by bellgrim** 2016-03-13 20:40 UTC
