### ISSUE TITLE
BUG: EdDSA keypair generation not works in multi-thread mode

### ISSUE THREAD

**Issue by xipki** [opendnssec/SoftHSMv2#485] opened 2019-06-21 17:41 UTC
The generation of EdDSA keypairs seems not to work in multi-threads mode. To reproduce the error, start 2 threads, each thread opens one new session, and all threads generate EdDSA keypairs. After a few rounds you get the GENERAL_ERROR. 

I am using OpenSSL 1.1.1b as crypto backend, and the OS is Ubuntu 19.04 64 bit.

**Comment by rijswijk** [comment] 2019-06-25 05:41
I have some questions:

- Can you test this with the support OpenSSL 1.1.1a on Ubuntu 18.04? (supported since mid June)
- Have you checked the SoftHSM debug log to see if that provides any additional information as to why the error occurs?
- Can you provide the test code that allows reproduction of the issue?
- Can you confirm that this issue only occurs with EdDSA?

**Comment by xipki** [comment] 2019-06-25 06:31
KeyPairGeneration for DSA, ECDSA and RSA without error. Only the performance of EC_KEYPAIR_GEN is very very slow (about 7 keypairs / second).

Related to the test code, I will come back later.

**Comment by rijswijk** [comment] 2019-06-27 05:41
In the original report you were talking about getting errors, but now you're saying EdDSA key generation is slow. I would say generating 7 keypairs per second is not necessarily slow, but why would you want to generate keys at that rate anyway? Unless there is an error condition that should not be occurring, I would be inclined to close this issue.

**Comment by xipki** [comment] 2019-06-27 06:11
I cannot reproduced the error anymore, so in this context this issue can be closed.

Related to the performance, this is indeed an topic unrelated to this issue. Generation of ECDSA/ECDSA under 10 per seconds is in many use cases not enough, especially for IoT. The provision server generates keypairs in HSM and then export then to the devices.

**Comment by rijswijk** [comment] 2019-06-27 06:15
Out of curiosity: have you tested with "real" HSMs what performance they can deliver, or by using a raw EdDSA implementation? It seems unlikely that the performance of EdDSA key generation is limited by any code in SoftHSM, more likely, it is the OpenSSL implementation that determines the performance. If you want really high speed, you could consider looking at e.g. [libsodium](https://github.com/jedisct1/libsodium).

**Comment by xipki** [comment] 2019-06-27 08:29
Sorry

**Closed** 2019-06-27 08:29 UTC

**Comment by xipki** [comment] 2019-06-27 08:34
Sorry I cannot test it with Real HSMs. After removing the C_FindObjects operations in my code, I got 120 keys generated per second. This is, however, far below the limit of openssl. I cannot find command to test the key generation, but the `openssl speed - multi 4 ed25519` shows ca. 300,000 signature creation operations.
